name: Run Postman Collection and Generate Allure Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Use a version compatible with Newman

    # Step 3: Install Newman and Allure Commandline
    - name: Install Dependencies
      run: |
        npm install -g newman newman-reporter-allure
        npm install -g allure-commandline --unsafe-perm

    # Step 4: Run Postman Collection using Newman
    - name: Run Postman Collection
      run: |
        newman run newmanTest_collection.json --reporters cli,allure || echo "Newman tests failed, continuing workflow."

    # Step 5: Generate Allure Report
    - name: Generate Allure Report
      run: |
        allure generate --single-file allure-results --clean -o allure-report

    # Step 6: Upload Allure Report as an Artifact
    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
